# Site settings
title: Tobey's chit chat
header-img: img/home-bg.jpg
email: apa915436@gmail.com
copyright_name: Tobey's personal blog
description: "This is apa915436's personal blog."
url: "http://yourdomain.com"
github_username:  apa915436
facebook_username:  tobey.yang.18
email_username:  apa915436@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]